### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by hexalellogram** [acmucsd/acm-profiles-ui#15]
Should be able to toggle search mode between users and communities

Before a search is conducted, it should show recommendations (get recommendations from the API)

From the design document:
Show recommendations until you do a search
Search for person or community
Dropdown to the right of the search bar - choose what to search for - separate results for each

**Comment by PatrickBrown1** [comment]
Currently working on this. Most of the front end work is done, I just need to access the backend to get recommendations and search results.
