### ISSUE TITLE
My Profile Page

### ISSUE THREAD

**Issue by hexalellogram** [acmucsd/acm-profiles-ui#16]
See Figma prototype for layout specifics: https://www.figma.com/proto/IBDOJxApCevq1jqnrMO27D/ACM-Profiles?node-id=3%3A27&scaling=contain

Should contain spaces for profile picture, name, year, major, bio, follow button (do not show if the user is viewing their own profile)

3 tabs below for contact information (showing their social media), a list of who follows them, and a list of who they are following

Should be able to add new social media from this page, if you are viewing your own page

**Comment by PatrickBrown1** [comment]
We also have to consider how we will change this information.

It will probably be an "edit my profile" button, where the text boxes will become editable. At the bottom, there will be a toolbar that will allow you to submit your changes. Once this button is clicked, it will push to the backend.

**Comment by jettbui** [comment]
Both of the main components for this page are being worked on ([MemberHeader](https://github.com/acmucsd/acm-profiles-ui/tree/create-member-header) and [TabbedLists](https://github.com/acmucsd/acm-profiles-ui/tree/tabbed-lists))

After that we'd have to get functionality working, including the toolbar/editability, as well as start working with the backend
