### ISSUE TITLE
Community Page

### ISSUE THREAD

**Issue by hexalellogram** [acmucsd/acm-profiles-ui#17]
See Figma prototype for layout specifics: https://www.figma.com/proto/IBDOJxApCevq1jqnrMO27D/ACM-Profiles?node-id=3%3A12&scaling=contain

Should have spaces for a profile picture, name of the community, and community description. Button to join the community should be visible if you are not already in the community, otherwise it should say leave community and let you leave

Two tabs below for contact information for the community (ex: social media for that organization, discord server link, etc.) as well as a list of members. Clicking on a member would take you to their profile page.

Should have an indicator in the members list to indicate who is a moderator.

Note: this is not in the prototype but we need a button (visible to moderators only) that lets them manage the details of the community like the description, contact information, etc.

**Comment by jettbui** [comment]
CommunityHeader is finished so I'm just waiting on [TabbedLists](https://github.com/acmucsd/acm-profiles-ui/tree/tabbed-lists) which would display the community's contact information and members list.

The layout and functionality will probably be similar to the profile page (#16) including the editing and toolbar aspect but instead it would work for all moderators that can edit the community.
