### ISSUE TITLE
Create new community?

### ISSUE THREAD

**Issue by hexalellogram** [acmucsd/acm-profiles-ui#18]
Was just looking through the prototype and I realized we don't really have a way to create a new community on the frontend (there's not button or page for that) so we need to figure out how we are going to do that.

**Comment by PatrickBrown1** [comment]
This could be added on the search page before the user searches

**Comment by hexalellogram** [comment]
@PatrickBrown1 Sounds good. I'll leave it to you whether you want to update our Figma design with that button or not or if you just want to add that into the search page.

**Comment by PatrickBrown1** [comment]
Will include a button before anything is searched and when a search comes up empty. When clicked, the button will prompt an input modal with inputs for the community name. The user who creates it will automatically become an admin.
